# Generated by Django 4.2.4 on 2023-08-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe_game', '0004_remove_partida_estado_tablero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
